version: '3.8'

services:
    app8.1:
        build:
            context: .
        container_name: diploma8.1
        working_dir: /var/www
        volumes:
            - app-data:/var/www
            - type: bind
              source: ./composer.json
              target: /var/www/composer.json
            - type: bind
              source: ./composer.lock
              target: /var/www/composer.lock
            - type: bind
              source: ./.env
              target: /var/www/.env
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./storage:/var/www/storage
            - ./config:/var/www/config
            - ./config:/var/www/config
            - ./app:/var/www/app
            - app-resources:/var/www/resources
            - ./routes:/var/www/routes
            - ./database:/var/www/database
            - ./lang:/var/www/lang
        ports:
            - "6001:6001"
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: diploma_webserver
        working_dir: /var/www
        volumes:
            - app-data:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:80"
        networks:
            - app-network
        depends_on:
            - app8.1

    db:
        image: mysql:5.7
        container_name: diploma_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: diploma_phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    app-data:
        driver: local
    app-lang:
        driver: local
    dbdata:
        driver: local
    app-app:
        driver: local
    app-storage:
        driver: local
    app-resources:
        driver: local
    app-routes:
        driver: local
    app-database:
        driver: local
    app-config:
        driver: local

